config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#index"

  devise_for :users

  get "profile", to: "profiles#show", as: "profile"
  get "profile/edit", to: "profiles#edit", as: "edit_profile"
  put "profile", to: "profiles#update"
  post "subscribe", to: "push_subscriptions#create"

  resources :chats, only: [:index, :show, :update, :new], param: :token do
    collection do
      get "search", to: "chats#search"
    end
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_secure_token

  has_many :chat_profiles, dependent: :destroy
  has_many :profiles, through: :chat_profiles
  has_many :messages, dependent: :destroy

  def recipient(sender_id)
    profiles.reject { |p| p.id == sender_id }.first
  end

  def self.find_chat_for_profiles(profile1, profile2)
    joins(:chat_profiles)
    .where(chat_profiles: { profile_id: [profile1.id, profile2.id] })
    .group("chats.id")
    .having("COUNT(DISTINCT chat_profiles.profile_id) = 2")
    .first
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  include FindProfile

  prepend_before_action :authenticate_user!
  before_action :set_chat, only: [:show, :update]
  before_action :set_recipient, only: [:show, :update]

  def index
    @chats = @profile.chats.includes(:profiles)
  end

  def show
    @messages = @chat.messages.includes(:profile).ordered
  end

  def update
    @message = @chat.messages.new(message_params)
    @message.profile = @profile

    if @message.save
      broadcast_new_message
      notify_recipient
    end
  end

  def search
    if params[:query].blank?
      @chats = @profile.chats.includes(:profiles)
      render partial: "chats/sidebar", locals: { items: @chats }
    else
      @profiles = Profile.search_except_self(params[:query], @profile.id)
    end
  end

  def new
    @recipient = Profile.find_by!(token: params[:token])
    @chat = Chat.find_chat_for_profiles(@profile, @recipient)
    @chat ||= Chat.create(profiles: [@profile, @recipient])
    @messages = @chat.messages.includes(:profile).ordered
    render :show
  end

  private

  def broadcast_new_message
    BroadcastService.new(@profile, @recipient, @chat).notify
  end

  def notify_recipient
    return if @recipient.subscription.blank?

    message = {
      title: "You have a new message!",
      options: {
        body: "#{@profile.name} sent you a message",
        data: { path: chats_path }
      }
    }

    PushNotificationService.new(@recipient.subscription, message).notify
  end

  def set_chat
    @chat = @profile.chats.find_by!(token: params[:token])
  end

  def set_recipient
    @recipient = @chat.recipient(@profile.id)
  end

  def message_params
    params.require(:messages).permit(:content)
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
  def user_icon(profile, class_names = "size-10")
    return if profile.blank?

    content_tag :div, class: [class_names, "flex-shrink-0 rounded-full bg-blue-500 text-white flex items-center justify-center"] do
      profile.name.first
    end
  end

  def message_content(message, its_me)
    return if message.blank?

    class_names = its_me ? "bg-blue-500 text-white" : "bg-gray-200 text-gray-800"
    content_tag :div, class: ["rounded-3xl px-5 py-2.5 sm:max-w-lg", class_names] do
      content_tag :p, message.content, class: "text-sm"
    end
  end
end

app/views/chats/_chat.html.erb
<% recipient = recipient || chat.recipient(profile_id) %>
<% new_msg = new_msg || false %>

<%= link_to chat_path(chat.token), id: "chat_#{chat.token}", data: { turbo_frame: "chat_details" } do %>
  <div class="cursor-pointer p-4 border-b hover:bg-blue-50 flex items-center">
    <%= user_icon(recipient) %>
    <div class="ml-3 grow">
      <p class="text-sm font-medium text-gray-900"><%= recipient.name %></p>
      <p class="text-xs text-gray-500">@<%= recipient.nickname %></p>
    </div>
    <% if new_msg %>
      <div class="new-message-badge">
        <div class="size-4 rounded-full bg-green-600"> </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/chats/_chat_item.html.erb
<%
  new_msg = local_assigns.fetch(:new_msg, false)
  chat = local_assigns.fetch(:chat, nil)
  if chat.present?
    path = chat_path(chat.token)
  else
    path = new_chat_path(token: recipient.token)
  end
%>

<%= link_to path, id: "recipient_#{recipient.token}", data: { turbo_frame: "chat_details", turbo_prefetch: false } do %>
  <div class="cursor-pointer p-4 border-b hover:bg-blue-50 flex items-center">
    <%= user_icon(recipient) %>
    <div class="ml-3 grow">
      <p class="text-sm font-medium text-gray-900"><%= recipient.name %></p>
      <p class="text-xs text-gray-500">@<%= recipient.nickname %></p>
    </div>
    <% if new_msg %>
      <div class="new-message-badge">
        <div class="size-4 rounded-full bg-green-600"> </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/chats/_message.html.erb
<% its_me = message.profile_id == @profile.id %>
<%= content_tag :div, class: ["flex items-start mb-4", { "justify-end": its_me }] do %>
  <%= user_icon(message.profile, "size-8") unless its_me %>
  <div class="mx-3">
    <%= message_content(message, its_me) %>
    <p class="text-xs text-gray-400 mt-1"><%= to_datetime(message.created_at) %></p>
  </div>
  <%= user_icon(message.profile, "size-8") if its_me %>
<% end %>

app/views/chats/_message_input.html.erb
<%# locals: (with_error: false) %>
<% class_names = with_error ? "border-2 border-rose-500 focus:border-2 focus:border-rose-500" : "border-none" %>
<div class="p-4 border-t bg-white" id="message-input">
  <%= form_with model: @chat, url: chat_path(@chat.token), method: :put, class: "flex" do |f| %>
    <%= fields_for :messages, Message.new do |m| %>
      <%= m.text_field :content,
                        autofocus: true,
                        autocomplete: "off",
                        required: true,
                        placeholder: "Write a message...",
                        class: [class_names, "flex-1 px-4 py-2 placeholder:text-gray-400 focus:outline-none focus:ring-0"] %>
    <% end %>
    <%= f.submit "Send", class: "ml-3 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-500" %>
  <% end %>
</div>

app/views/chats/_search_bar.html.erb
<%= form_with url: search_chats_path, method: :get, class: "relative p-4 h-20 flex items-center border-t border-t-blue-50 border-b border-b-blue-100", data: { turbo_frame: "sidebar_chats" } do %>
  <%= text_field_tag :query,
                      params[:query],
                      autocomplete: "off",
                      placeholder: "Search users...",
                      class: "w-full px-4 py-2 border-none bg-gray-100 placeholder:text-gray-400 rounded-full focus:outline-none focus:border-blue-200" %>
  <%= button_tag type: "submit", name: nil, class: "absolute inset-y-0 right-0 flex items-center pr-7" do %>
    <%= inline_svg_tag("search.svg", class: "w-5 h-5 text-gray-500 hover:text-blue-500 transition duration-150") %>
  <% end %>
<% end %>

app/views/chats/_sidebar.html.erb
<%= turbo_frame_tag :sidebar_chats do %>
  <% items.each do |item| %>
    <% if item.is_a?(Chat) %>
      <%= render partial: "chat_item", locals: {
        chat: item,
        recipient: item.recipient(@profile.id),
        profile: @profile
      } %>
    <% else %>
      <%= render partial: "chat_item", locals: {
        recipient: item
      } %>
    <% end %>
  <% end %>
<% end %>

app/views/chats/index.html.erb
<% content_for :sidebar do %>
  <div class="w-1/4 bg-white overflow-y-auto shadow-inner" data-controller="notifications-subscribe" data-notifications-subscribe-api-key-value="<%= Base64.urlsafe_decode64(Rails.application.credentials.dig(:vapid, :public_key)).bytes %>">
    <%= render partial: "search_bar" %>

    <%= turbo_stream_from "sidebar_profile_#{@profile.nickname}" %>
    <%= render partial: "sidebar", locals: { items: @chats } %>
  </div>
<% end %>

<%= turbo_frame_tag :chat_details, refresh: :morph %>

app/views/chats/search.html.erb
<% if @profiles.any? %>
  <%= render partial: "sidebar", locals: { items: @profiles } %>
<% else %>
  <%= turbo_frame_tag :sidebar_chats do %>
    <p class="p-4">No users found</p>
  <% end %>
<% end %>

app/views/chats/show.html.erb
<%= turbo_frame_tag :chat_details, refresh: :morph do %>
  <%= turbo_stream_from @chat %>
  <div class="p-4 h-20 border-b border-blue-100 bg-blue-50 flex items-center">
    <%= user_icon(@recipient) %>
    <div class="ml-3">
      <p class="text-sm font-medium text-gray-900"><%= @recipient.name %></p>
    </div>
  </div>

  <%= content_tag :div, class: "flex-1 p-4 overflow-y-auto", id: "messages",
                  data: { controller: "chat-display",
                          chat_display_token_value: @recipient.token,
                          chat_display_target: "messagesContainer" } do %>
    <%= render partial: "message", collection: @messages %>
  <% end %>

  <%= render partial: "message_input" %>
<% end %>

app/views/chats/update.turbo_stream.erb
<%= turbo_stream.append("messages", partial: "message", locals: { message: @message }) if @message.errors.empty? %>
<%= turbo_stream.replace("message-input", partial: "message_input", locals: { with_error: @message.errors.any? }) %>