config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#index"

  devise_for :users

  get "profile", to: "profiles#show", as: "profile"
  get "profile/edit", to: "profiles#edit", as: "edit_profile"
  put "profile", to: "profiles#update"
  post "subscribe", to: "push_subscriptions#create"

  resources :chats, only: [:index, :show, :update, :new], param: :token do
    collection do
      get "search", to: "chats#search"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Message Me" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col min-h-screen bg-gradient-to-b from-white to-blue-50">
    <header class="flex justify-between items-center p-6 bg-white">
      <div class="text-2xl font-medium text-blue-600"><%= link_to "MessageMe", root_path %></div>
      <div class="flex items-center gap-x-4">
        <% if user_signed_in? %>
          <%= link_to "Your profile", profile_path, class: "inline-block rounded-full py-2 px-4 text-sm text-slate-700 hover:bg-slate-100 hover:text-slate-900" %>
          <%= link_to "Send a message", chats_path, class: "inline-block rounded-full py-2 px-4 text-sm font-semibold bg-blue-600 text-white hover:text-slate-100 hover:bg-blue-500" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "inline-block rounded-full py-2 px-4 text-sm text-slate-700 hover:bg-slate-100 hover:text-slate-900" %>
          <%= link_to "Get started", new_user_registration_path, class: "inline-block rounded-full py-2 px-4 text-sm font-semibold bg-blue-600 text-white hover:text-slate-100 hover:bg-blue-500" %>
        <% end %>
      </div>
    </header>
    <%= content_tag :main, class: [{"flex-1 flex": content_for?(:sidebar)}] do %>
      <%= yield :sidebar %>
      <%= yield %>
    <% end %>
  </body>
</html>